### ISSUE TITLE
Create user does not set roles 

### ISSUE THREAD

**Issue by hantsy** [FusionAuth/fusionauth-java-client#24] opened 2022-03-16 13:14 UTC
In my project I have built the following request object using Kotlin.  The Java Client version I was using is [1.34.1](https://github.com/FusionAuth/fusionauth-java-client/releases/tag/1.34.1)

```kotlin
// data is a pojo from a method of my service.
        val request = UserRequest(
            User().apply {
                email = data.email
                mobilePhone = data.phoneNumber
                firstName = data.firstName
                lastName = data.lastName
                password = randomAlphanumericString(8)
                username = data.firstName.lowercase() + "_" + randomAlphanumericString(6)
                registrations.add(
                    UserRegistration().apply {
                        roles =sortedSetOf("ROLE_USER")
                        applicationId = myapplicationId 
                    }
                )
            }
        ).apply { applicationId = myapplicationId }
        log.debug("create user request: $request")
        client.createUser(UUID.randomUUID(), request)  
```

When it is executed, I found I can not get roles from the `response.user.getRolesOfApplicaiton()`. It seems the uesr registration data in the user request is no use at all.

**Comment by hantsy** [comment] 2022-03-17 01:21
If it is not existed, it will fail with errors. Currently I found, the `registrations` of the User is not applied at all.

**Comment by hantsy** [comment] 2022-03-17 03:16
My testing result is like.

1. `createUser` using above data, and getRolenamesofApplication of the response.user return `null`, then invoke `retrieveUser` using the returned user.userid in last step and call getRolenamesofApplication of the response.user returns `null`.
2. `register` using data in the issue #25 , and getRolenamesofApplication of the response.user return `null`, then invoke `retrieveUser` using the returned user.userid in last step and call getRolenamesofApplication of the response.user returns the correct role names.

**Comment by robotdan** [comment] 2022-03-26 16:47
This is working as designed, if you want to create a user and a registration at the same time, you need to use the Register API. 

See `register(UUID userId, RegistrationRequest request)` in the Java Client. 

If that doesn't work let us know!

**Comment by mooreds** [comment] 2022-05-02 21:12
@hantsy I'm going to close this since it is working as designed. Please re-open if I've closed it in error.

**Closed by mooreds** 2022-05-02 21:12 UTC
