### ISSUE TITLE
username in user registration is no use when registering a user

### ISSUE THREAD

**Issue by hantsy** [FusionAuth/fusionauth-java-client#25] opened 2022-03-16 13:20 UTC
I was trying to use `register` to add a new user.

```kotlin 
        val request = RegistrationRequest(
            User().apply {
                firstName = data.firstName
                lastName = data.lastName
                email = data.email
                mobilePhone = data.phoneNumber
                password = randomAlphanumericString(8)
                username = data.firstName.lowercase() + "_" + randomAlphanumericString(6)
            },
            UserRegistration().apply {
                roles =sortedSetOf<String>("ADMIN")
                applicationId = mapplicationId
                // if set here, username is not stored.
                // username = data.firstName.lowercase() + "_" + randomAlphanumericString(6)
            }
        )
            client.register(UUID.randomUUID(), request)

```

If I put the username in the `UserRegistration`, the result will not contain the username. I have to put it into the User object.

Here `register` will affect the getRolesOfApplication. 

I really do not understand the APIs provided in the Java Client.  I can not imagine a request object contains so many fields, but most of them are no use.

**Comment by mooreds** [comment] 2022-03-16 14:03
Hi @hantsy . Thanks for using FusionAuth!

The username in the registration is for display purposes only. From the [registrations documentation[(https://fusionauth.io/docs/v1/tech/apis/registrations), `registration.username`.

> The username of the User for this Application. This username cannot be used to login. It is for display purposes only. The user.username field may be used to login.

So this field lets you have users with different display names in different applications (mooreds in a forum, dan.moore in a support ticket system, etc).

Hope that clears this up. I'm going to close out this issue.

**Comment by hantsy** [comment] 2022-03-17 01:17
What I used `username` is in the `register` method, you can see the codes.

**Comment by hantsy** [comment] 2022-03-17 01:33
For each endpoints, every field of the request object should be affected if assigning a value.

**Comment by mooreds** [comment] 2022-03-31 23:22
> For each endpoints, every field of the request object should be affected if assigning a value.

I'm not sure I understand the issue. Can you please share some code snippets?

**Comment by mooreds** [comment] 2022-03-31 23:24
I see some code snippets above, but I'm not clear on which username is not stored if you uncomment `username` in `UserRegistration`. Is there a value on `user.username`, `user.registration.username`, both or none?

**Comment by mooreds** [comment] 2022-05-02 21:51
So I just tried to replicate with this code:

```
package io.fusionauth.example;

import java.util.UUID;
import com.inversoft.error.Errors;
import io.fusionauth.client.FusionAuthClient;
import io.fusionauth.domain.User;
import io.fusionauth.domain.UserRegistration;
import io.fusionauth.domain.api.user.RegistrationRequest;
import io.fusionauth.domain.api.user.RegistrationResponse;
import com.inversoft.rest.ClientResponse;
import java.util.*;

public class RegisterUser {

    public static void main(String[] args) {

        ApplicationProperties.setupProperties();

        // Initiating the client
        FusionAuthClient client = new FusionAuthClient(ApplicationProperties.getApiKey(),
                ApplicationProperties.getFusionAuthURL());

        // Initiating the user and providing registration details
        User javauser = new User();
        javauser.email = "test3@example.com";
        javauser.password = "password";
        javauser.lastName = "last";
        javauser.firstName = "first";
        javauser.username = "username3";

        // Initiating user registration and creating request object
        UserRegistration userreg = new UserRegistration();
        userreg.applicationId = UUID.fromString("20ce6dac-b985-4c77-bb59-6369249f884b");
        SortedSet<String> roles = new TreeSet<String>();
        roles.add("ADMIN");
        userreg.roles = roles;
        userreg.username = "regusername3";

        RegistrationRequest request = new RegistrationRequest(javauser, userreg);

        // Using the returned ClientResponse object
        ClientResponse<RegistrationResponse, Errors> response = client.register(null, request);

        if (response.wasSuccessful()) {
            System.out.println("Registration successful");

        } else {
            // Handling errors
            System.out.println(response.errorResponse);
        }
    }

}
```

And I was able to provide the username on the user object as well as on the registration object. 

I'm going to close this since I can't reproduce. Please re-open if you can provide replication steps or if I misunderstand the issue.

**Closed by mooreds** 2022-05-02 21:51 UTC
